# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod 'Google/SignIn'
pod 'Google/Analytics'

target 'Minute Tutor' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Minute Tutor

  target 'Minute TutorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Minute TutorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
